sharding:
  jdbc:
    datasource:
      names: m1
      m1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: org.h2.Driver
        url: jdbc:h2:mem:testdbsa;DB_CLOSE_DELAY=-1
        username: sa
        password:
spring:
  h2:
    console:
      enabled: true
  main:
    allow-bean-definition-overriding: false
server:
  port: 8081