server:
  port: 8081

spring:
  main:
    allow-bean-definition-overriding: false
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:dbsa;DB_CLOSE_DELAY=-1
    username: sa
    password:
